services:
  health_check.ez.search:
    class: FT\EzHealthCheckBundle\HealthChecks\SearchHealthCheck
    arguments:
      - "@ezpublish.api.repository"    
    tags: [{ name: health_check.configurable, priority: 200 }]

  health_check.ez.cache:
    class: FT\EzHealthCheckBundle\HealthChecks\PersistenceCacheHealthCheck
    arguments:
      - "@ezpublish.cache_pool"
    tags: [{ name: health_check.configurable, priority: 205 }]

  health_check.ez.database:
    class: FT\EzHealthCheckBundle\HealthChecks\DatabaseHealthCheck
    arguments:
      - "@doctrine.orm.entity_manager"
    tags: [{ name: health_check.configurable, priority: 210 }]
